before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/dotd/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
      - arm64
      - arm
      - ppc64le
    ignore:
      - goos: darwin
        goarch: 386
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Version }}-{{ .ShortCommit }}"

release:
  draft: true
  disable: true

brews:
  - skip_upload: true
    github:
      owner: adnsio
      name: homebrew-tap
    homepage: "https://github.com/adnsio/dotd"
    description: "Local proxy to DNS over HTTPS (RFC 8484) compatible servers"
    url_template: "https://github.com/adnsio/dotd/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    plist: |
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
        <dict>
          <key>KeepAlive</key>
          <true/>
          <key>Label</key>
          <string>#{plist_name}</string>
          <key>ProgramArguments</key>
          <array>
            <string>#{opt_bin}/dotd</string>
          </array>
          <key>RunAtLoad</key>
          <true/>
          <key>WorkingDirectory</key>
          <string>#{var}</string>
          <key>StandardErrorPath</key>
          <string>#{var}/log/dotd.log</string>
          <key>StandardOutPath</key>
          <string>#{var}/log/dotd.log</string>
        </dict>
      </plist>
    test: |
      system "#{bin}/dotd --version"
